"""Scientific MCP Contract v1. No dependency on MCP or a domain library."""

from .models import (
    CONTRACT_VERSION,
    ArtifactReference,
    CheckStatus,
    Completeness,
    ContractModel,
    DiagnosticCheck,
    Diagnostics,
    DiagnosticWarning,
    Equation,
    ErrorCategory,
    ErrorCode,
    Matrix,
    NumericalDiagnostics,
    Provenance,
    Scalar,
    ScientificContext,
    ScientificError,
    ScientificResult,
    Severity,
    SparseComponent,
    SymbolicExpression,
    Tensor,
    Vector,
    schema_for,
)

__all__ = [
    "CONTRACT_VERSION",
    "ArtifactReference",
    "CheckStatus",
    "Completeness",
    "ContractModel",
    "DiagnosticCheck",
    "Diagnostics",
    "DiagnosticWarning",
    "Equation",
    "ErrorCategory",
    "ErrorCode",
    "Matrix",
    "NumericalDiagnostics",
    "Provenance",
    "Scalar",
    "ScientificContext",
    "ScientificError",
    "ScientificResult",
    "Severity",
    "SparseComponent",
    "SymbolicExpression",
    "Tensor",
    "Vector",
    "schema_for",
]
